// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvdBe0nBV7ZRJSq3_hcNTn-1g0wDyuOgs',
    appId: '1:824295242663:web:fe36004ba788e493589482',
    messagingSenderId: '824295242663',
    projectId: 'flutter-chart1',
    authDomain: 'flutter-chart1.firebaseapp.com',
    storageBucket: 'flutter-chart1.appspot.com',
    measurementId: 'G-XLTKEH06RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOuqofAvISp64PXXVkYZ5W0eaYhVvEOJA',
    appId: '1:824295242663:android:da92656acbc6c926589482',
    messagingSenderId: '824295242663',
    projectId: 'flutter-chart1',
    storageBucket: 'flutter-chart1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt5dWuZhDfac4gw35beChnRD0EHvnAaJw',
    appId: '1:824295242663:ios:f45f712f7598ea9c589482',
    messagingSenderId: '824295242663',
    projectId: 'flutter-chart1',
    storageBucket: 'flutter-chart1.appspot.com',
    iosClientId: '824295242663-c8m2e9r37br7hm34qt325etjede146hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt5dWuZhDfac4gw35beChnRD0EHvnAaJw',
    appId: '1:824295242663:ios:fa8ed1f6d40cbe1a589482',
    messagingSenderId: '824295242663',
    projectId: 'flutter-chart1',
    storageBucket: 'flutter-chart1.appspot.com',
    iosClientId: '824295242663-38mat9b7istfbts68i1u1u89nvhjbvb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
